---
name: kafka
logging:
   level: debug
director_uuid: <%= `bosh status --uuid` %>
release:
  name: kafka
  version: 0+dev.2

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000 - 240000
  update_watch_time: 30000 - 600000
  max_in_flight: 2

jobs:
 - name: zookeeper
   templates:
   - name :  zookeeper
   instances: 1
   vm_type: small
   persistent_disk: 4096
   stemcell: trusty
   azs: [z0]
   networks:
   - name: private
     static_ips: [10.255.0.110]

 - name: broker
   templates:
   - name: broker
   instances: 2
   vm_type: small
   persistent_disk: 10000
   stemcell: trusty
   azs: [z0]
   networks:
   - name: private

properties:
  zookeeper: 10.255.0.110
